ObolNetwork/charon-distributed-validator-node

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Testing out if we want to bring in a feature like this into charon to streamline issue creation into more than just Problem to be solved, proposed solution issues.
=> Add issue templates to this repo

README.md
- Removed Obol Team member will do Step 2 `create DKG` as number of cluster won't allow us in terms of resources
- Added the need to submit deposit and cluster files after DKG
=> Update readme to align with Athena planning

.env.sample, docker-compose.yml
- Update versions of teku and charon
- Replace ghcr with dockerhub
=> update charon version to v0.9.0 and teku version to 22.7.0

.env.sample, README.md, prometheus/prometheus.yml
Adds remote prometheus configuration to push metrics to central prometheus service.
ticket: #8
=> add remote prometheus config

.env.sample, README.md, docker-compose.yml
Move charon flags from `.env` file to `docker-compose.yml` file
=> move charon flags from env file to docker-compose

README.md
Add fee recipient address and withdrawal address to create dkg
=> add fee and withdrawal address

README.md, config/teku_config.yaml
Replace `--network` value from `auto` to `goerli`.
=> fix teku vc

.github/workflows/add_issue_to_project.yml, .github/workflows/blank.yml
This is a basic workflow adding every issue in this repo to the new Project Management Board. Still needs personal access token to be added
=> Action to add new issues to project

README.md
Reflecting latest annoucements for the public track using team captains instead of only Obol team members
=> update Readme with team captains

docker-compose.yml
- upgrade `lighthouse` to `2.5.1` (https://github.com/sigp/lighthouse/releases/tag/v2.5.1).
- upgrade `teku` to `22.8.0` (https://github.com/ConsenSys/teku/releases/tag/22.8.0).
=> upgrade lighthouse and teku

.env.sample
Many users unclear on how to paste the enrs
=> Clarify ENR comments based on frequent issue

docker-compose.yml
Adds charon port bindings to docker-compose.yml.
Fixes #59
=> Adds charon port bindings to docker-compose.yml

README.md, bootnode/docker-compose.yml
Fixes issues with bootnode compose file.
=> fix bootnode compose file

.gitignore, data/grafana/sample, data/prometheus/sample, docker-compose.yml
=> mount volume to persist prometheus and grafana data

grafana/dashboards/single_node_dashboard.json
Solves #49 
Also adds panels to show attestations and blocks submitted by bcast to beacon node.
=> add participation panel

.gitignore, data/grafana/sample, data/prometheus/sample, docker-compose.yml
Fix permission issues in `grafana` and `prometheus`.
=> fix grafana and prometheus bug in linux

README.md, compose-voluntary-exit.yml, docker-compose.yml
Adds support for voluntary exits.
Also use charon image from dockerhub.
=> add support for voluntary exits

docker-compose.yml, grafana/dashboards/single_node_dashboard.json
* Updates charon version to v0.10.0
* Prometheus version to v2.38.0. Also updates and add some panels. 
* Current dashboard looks like:
=> update charon version to v0.10.0

.gitignore, README.md, bootnode/docker-compose.yml, config/teku_config.yaml, docker-compose.yml
* upgrade versions of `lighthouse`, `teku` and `geth` to their latest release.
* change network from `goerli` to `auto` in teku config.
Teku: https://github.com/ConsenSys/teku/releases
Lighthouse: https://github.com/sigp/lighthouse/releases/tag/v3.0.0
Geth: https://github.com/ethereum/go-ethereum/releases
=> upgrade versions

grafana/dashboards/single_node_dashboard.json
Adds validator balance panel to grafana dashboard.
=> add validator balance

docker-compose.yml, grafana/dashboards/single_node_dashboard.json
Fixes #43 
This is how our dashboard looks like
=> add beaconcha.in URIs to dashboard

docker-compose.yml, grafana/dashboards/single_node_dashboard.json
Add `threshold`, `num operators` and `peer name` to single node charon dashboard.
category: dashboard
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/65
=> Add metrics to node dashboard

docker-compose.yml
Fixes Lighthouse p2p port mappings from 30303 to 9000.
=> fix lighthouse p2p ports

grafana/dashboards/single_node_dashboard.json
=> fix app info panel

docker-compose.yml
Bumps charon version from v0.10.0 to v0.10.1
=> bump charon version to v0.10.1

teku/teku_config.yaml
=> disable teku keystore locking

README.md, bootnode/docker-compose.yml, grafana/dashboards/dash_charon_overview.json
Bumps charon version for `v0.11.0` release. Also, updates charon overview dashboard with compose dashboard.
=> bump charon version for `v0.11.0` release

README.md, bootnode/docker-compose.yml, docker-compose.yml
Reverts charon version from v0.11.0 back to v0.10.1
=> revert to v0.10.1

docker-compose.yml, grafana/dashboards/dash_charon_overview.json
Configures jaeger to use disk storage.
Also updates to latest overview dash which included uptime.
=> Configure jaeger disk storage

docker-compose.override.yml.sample
Fixes lighthouse port mappings.
=> fix lighthouse ports

README.md, bootnode/docker-compose.yml, docker-compose.yml, grafana/dashboards/dash_charon_overview.json, grafana/dashboards/logs_dashboard.json
Bumps charon version to v0.12.0
=> bump charon version to v0.12.0

grafana/dashboards/dash_charon_overview.json
Fixes grafana panel to handle uptime metrics for charon versions < `v0.11.0`.
=> modify grafana panel

compose-debug.yml, docker-compose.override.yml.sample, prometheus/prometheus.yml
=> add cadvisor to debug compose

docker-compose.yml
=> replace on-failure with unless-stopped

compose-debug.yml, compose-voluntary-exit.yml, docker-compose.yml
=> bump container versions

.env.sample, bootnode/docker-compose.yml, compose-debug.yml, docker-compose.yml, relay/docker-compose.yml
- Bumps charon version
- Update flags
- Rename bootnode to relay
- move loki to debug compose
=> refactor for v0.13.0 release

.env.sample, docker-compose.override.yml.sample, docker-compose.yml, mevboost-compose.yml
Adds `mev-boost` container.
category: feature
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/158
=> add mev-boost

prometheus/prometheus.yml
=> restrict remote write of metrics other than charon

.gitignore, docker-compose.yml, teku/teku_config.yaml
Adds slashing protection to teku VC.
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/125
=> add slashing protection to teku vc

.env.sample, compose-debug.yml, compose-voluntary-exit.yml, docker-compose.yml
Updates charon to v0.14.0 release. Also, updates other container versions.
=> update charon to v0.14.0

grafana/dashboards/dash_charon_overview.json
Adds latest charon overview dashboard as part of release process.
=> add latest charon overview dashboard

.env.sample, compose-debug.yml, compose-voluntary-exit.yml, docker-compose.yml, mevboost-compose.yml
Updates version of docker images and adds environment variables to switch networks.
ticket: #179
=> prepare for mainnet shapella

grafana/dashboards/dash_charon_overview.json
Updates readyz panel to latest thresholds.
=> update charon overview dashboard

grafana/dashboards/dash_charon_overview.json
Adds voluntary exit panel to Charon Overview dashboard.
=> Add voluntary exit panel to Charon Overview dashboard

grafana/dashboards/single_node_dashboard.json
Replaces teku panels with lodestar ones.
Ticket: #198
=> replace teku panels with lodestar ones

docker-compose.yml, grafana/dashboards/dash_charon_overview.json
Fixes beacon node score panel.
ticket: #205
=> grafana: fix beacon node score panel

.env.sample, docker-compose.yml
Bump CDVN to latest `charon` release `v0.17.0`. Also, bump `geth` & `lodestar` to respective latest versions.
=> bump charon to latest release

.env.sample, docker-compose.yml
Tags charon service with v0.17.1 tag.
=> tag charon with v0.17.1

README.md
Updated two links in the readme to work with new/upcoming versions of the docs
=> Updated two links in the readme

docker-compose.yml, lodestar/run.sh
Enable produceBlockV3 in lodestar as well.
=> *: update stack version for v1

lodestar/run.sh
Change builderonly to builderalways for lodestar
=> Change builderonly to builderalways for lodestar

.env.sample, .gitignore, docker-compose.yml, prometheus/prometheus.yml.example, prometheus/run.sh
Evaluate env vars in `prometheus.yml`.
ticket: #289
=> *: evaluate env variables in prometheus.yml

.env.sample.mainnet, docker-compose.yml
Reminded i forgot to PR this when I tried it when I encountered another user with the same issue.
=> Update titan relay, extend checkpoint sync timeout

.env.sample.holesky, .env.sample.mainnet, docker-compose.yml
Add `CHARON_NICKNAME` to env samples and docker compose env variables.
=> feat: charon nickname env variable

.env.sample.hoodi, docker-compose.yml, relay/docker-compose.yml
- Bump charon to v1.3.0
- Add Hoodi sample
=> *: bump charon to v1.3.0

docker-compose.yml, relay/docker-compose.yml
Bump Charon version to `v1.6.0`
=> Bump to v1.6.0
