README.md

Replace `git@github.com:ObolNetwork/charon-distributed-validator-node.git` with `https://github.com/ObolNetwork/charon-distributed-validator-node.git` as the former one won't work who are not part of obol org.

Correct repo link

---

README.md

Updates readme to v0.9.0, replace ghcr image with dockerhub image and add --p2p-bootnode-relay flag to dkg command.

update readme to v0.9.0

---

README.md

- Add caution for mounting lighthouse from locally synced LH BN.
- Add note for copying an already synced geth node which makes things faster.

add note for lighthouse and geth

---

grafana/dashboards/single_node_dashboard.json

﻿Currently the failed tracker grows indefinitely for failed attestations. Wrapping the command in `increase()[interval]` makes it more easy to see what's going wrong.

Improve failed duty panel

---

docker-compose.yml
grafana/dashboards/single_node_dashboard.json

Corver added a new feature to test your nodes autonat ability. This adds the same panel to the public dashboard,  such that we can gradually gather some data points as people post screenshots of their dashboard. Also breaks the dashboard into rows. My hope is this starts showing data when there are multiple nodes in this cluster speaking this new version?

Add NAT panel to dashboard

---

README.md
bootnode/docker-compose.yml

- Adds a `docker-compose.yaml` file for running charon bootnodes on your own

add docker compose for charon bootnode

---

README.md
bootnode/docker-compose.yml

Fixes bootnodes missing `.charon` volume removed during previous cleanup.

bootnode: fix missing private key folder

---

docker-compose.yml

Thank you for your great work! I’m very excited to be a part of this project! With the current setup, the lighthouse is not saving its data into a docker volume. That data is discarded during the restart or shutdown of the lighthouse container. And because of this, the lighthouse downloads the whole database after each restart. That creates unnecessary load on the local disc subsystem (high I/O and excessive wear of the SSD) and it generates additional traffic on the network. Also, this behaviour is causing the filesystem to grow in the docker root directory and not in ./data/lighthouse as you may expect.

Keep lighthouse data persistent between restarts.

---

.env.create_dkg.sample
.env.sample
README.md
docker-compose.yml

Refactors the `docker-compose.yml` file to contain defaults that can be overwritten in the `.env` file.
This aims to keep custom config away from the checked-in "official" config. Users should be able to update to latest by `git pull` without any merge conflicts since their custom config would not interfere. It also allows Obol to define default values while users can still overwrite them.
Fixes: #87

Refactor env file and default config

---

.env.sample
README.md
compose-voluntary-exit.yml
docker-compose.yml

Refactors exit compose file to use overridable custom env vars.
Update readme
Update teku and lighthouse versions

Align exit compose file with custom env var pattern

---

.env.sample
README.md
docker-compose.yml

Add support for any custom charon config flags without modifying `docker-compose.yml`.

support any custom charon config

---

README.md

It doesnt work with 436764: anymore, but works without

remove 436764: before monitoring token

---

.env.sample
README.md
docker-compose.yml

Removes the custom config env-file override which doesn't work if the override isn't present.
This cases the `ERROR: /Users/path/charon-distributed-validator-node is not a file.`

remove broken env-file option

---

.gitignore
docker-compose.override.yml.sample
docker-compose.yml

Adds support for a `docker-compose.override.yml` file to disable services in the stack. Also add a sample file with instructions on how it works.
Remove `depends_on` in docker-compose since:
- It creates very strong coupling between services
- Which cannot be removed by a override file

Support docker-compose.override.yml

---

README.md
grafana/dashboards/single_node_dashboard.json
prometheus/prometheus.yml

Remove `external_label` from `prometheus.yml` since charon now pushes cluster identifier labels (`cluster_name`, `cluster_hash`) and node identifier label (`peer_name`). Update dashboard.

remove external label from prometheus config

---

compose-voluntary-exit.yml
grafana/dashboards/dash_charon_overview.json
grafana/dashboards/logs_dashboard.json
grafana/dashboards/single_node_dashboard.json
grafana/datasource.yml

Copies the "charon overview dashboard" (previously called simnet dashboard) from charon repo (without modifications). 
Align datasource `uid`s so copying dashboards from other repos works.

adds charon overview dashboard

---

bootnode/docker-compose.yml

Reverts ObolNetwork/charon-distributed-validator-node#119

Bump charon version to `v0.11.0`

---

compose-voluntary-exit.yml

Removes keystore locking flag voluntary-exit command of teku in `compose-voluntary-exit.yml`.

remove keystore locking flag from voluntary-exit command

---

README.md

Removes the last reference of infura from the docs.
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/113

docs: remove infura from readme

---

docker-compose.override.yml.sample

Fixes comment spaces to differentiate between a "comment" and a "commented variable".

fix comment spaces

---

.env.sample
docker-compose.override.yml.sample
docker-compose.yml

Exposes host ports for P2P inbound communication for geth, lighthouse and charon docker containers.
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/128

expose p2p ports

---

.env.sample
docker-compose.yml
relay/docker-compose.yml

Discv5 UDP has been removed after v0.13. So remove all references.

remove discv5 UDP references

---

.env.sample
docker-compose.yml

Updates geth to [v1.11.4](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.4) and charon to `v0.14.1`.

update geth and charon versions

---

docker-compose.yml

Should not affect any user negatively, but helps have some requirements in place for certain network configurations, and multiple colo'd nodes in a cluster, etc.

Make Charon TCP port consistent internally/externally

---

.env.sample
docker-compose.yml

Updates checkpoint-sync URL for lighthouse as the old one is returning dns errors. Also adds an environment variable to override checkpoint-sync URL without changing docker-compose.yml

update checkpoint-sync URL

---

.env.sample
docker-compose.yml

Bump docker image versions for `lighthouse` BN and `teku` VC.
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/189

bump versions

---

lodestar/run.sh

Process started with `exec` will receive the signals sent to the PID. This makes sure that the process is exited gracefully and all cleanup tasks are completed, e.g. unlocking keystores.

Ensure Lodestar VC process exits gracefully

---

docker-compose.yml

Updates lodestar image version to v1.9.2 which contains latest builderonly flag.

update lodestar version to v1.9.2

---

docker-compose.yml

Add network `dv-node` to mev-boost container image.
This fixes the bug in which lighthouse container wasn't able to communicate with the mev-boost container which resulted in logs like:
```
{"code":500,"message":"INTERNAL_SERVER_ERROR: HttpClient(url: http://mev-boost:18550/, kind: request, detail: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution)","stacktraces":[]}
```

add network to mev-boost

---

.env.sample
docker-compose.override.yml.sample
docker-compose.yml

Added the commented docker hint because its been sitting on my staged changes for this repo for maybe a year almost

Update to v0.19.0

---

examples/lighthouse/run.sh

I wasn't able to get the lighthouse VC running without the datadir here.

lighthouse validator import was missing datadir

---

lodestar/run.sh

We switched from alpine to debian in our latest release (v1.21.0). The current entrypoint script uses syntax which is not POSIX-compliant and the script will fail to execute.
```
Importing key /home/charon/validator_keys/keystore-0.json
/opt/lodestar/run.sh: 6: [[: not found
/opt/lodestar/run.sh: 15: Bad substitution
```
This change does not require to bump the Lodestar version the script will still work with older releases.

Use POSIX-compliant syntax in Lodestar entrypoint script

---

lodestar/run.sh

Lodestar does not natively support importing keystores with different password in an efficient way right now (see https://github.com/ChainSafe/lodestar/issues/5249) that's why each keystore is imported individually right now via `validator import` command, but this is really slow, and redundant if keystores already exist after first startup.
We can speed this up significantly by directly writing keystores in Lodestar persistent keys backend, the outcome is exactly the same, we skip keys that are already imported, and put them into `keystoresDir` and `secretsDir` of Lodestar in the expected format.
This is the approach described in [protolambda/eth2-val-tools](https://github.com/protolambda/eth2-val-tools?tab=readme-ov-file#lodestar) and there is no downside in doing it like this.
It could …

Speed up Lodestar keystore import

---

docker-compose.yml

Bump charon to latest release which is now v1.0.1:
- https://github.com/ObolNetwork/charon/releases/tag/v1.0.1
- https://hub.docker.com/layers/obolnetwork/charon/v1.0.1/images/sha256-941893dd41ec0981244537028174e4857236d203a8741829a3b36d5cbcbdb221?context=explore

Bump charon to v1.0.1 in docker-compose.yml

---

docker-compose.yml

Bump charon version to v1.1.0. Bump also Lighthouse to v5.3.0 and Lodestar to v1.20.2 - versions with which charon v1.1.0 was tested.

Bump charon to v1.1.0

---

prysm/run.sh

Updated the documentation URL from https://docs.prylabs.network/docs to https://prysm.offchainlabs.com/docs and new urls paths.

docs: :memo: update Prysm domain to prysm.offchainlabs.com
